version: '3'

services:
  postgres:
    build: ./envDocker/img-postgre-custom
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: lorenzo
      POSTGRES_PASSWORD: nefaissurtoutpasca
      POSTGRES_DB: LordOfDarkness
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - envdocker_my_network

  # build_frontend:
  #   container_name: build_frontend
  #   build: ../front
  #   volumes:
  #     - ../front:/app
  #     - frontend_prod:/prod
  #   command: sh -c "cp -r /app/dist/* /prod/ && tail -f /dev/null"

  nginx:
    build: ./
    restart: always
    container_name: nginx
    ports:
      - "3100:80"
    depends_on:
      - postgres
    networks:
      - envdocker_my_network

  api:
    build: ./back
    restart: always
    container_name: api
    ports:
      - "3200:3200"
    networks:
      - envdocker_my_network

networks:
  envdocker_my_network:
    driver: bridge

volumes:
  postgres_data:
  frontend_prod:
