version: '3'

services:
  postgres:
    build: ./img-postgre-custom
    container_name: postgres
    environment:
      POSTGRES_USER: lorenzo
      POSTGRES_PASSWORD: nefaissurtoutpasca
      POSTGRES_DB: LordOfDarkness
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - envdocker_my_network

  nginx:
    build: ./img-nginx-custom
    container_name: nginx
    ports:
      - "3100:80"
    depends_on:
      - postgres
    networks:
      - envdocker_my_network

  api:
    build: ./img-api
    container_name: api
    ports:
      - "3200:3200"
    networks:
      - envdocker_my_network

networks:
  envdocker_my_network:
    driver: bridge

volumes:
  postgres_data:
