version: '3'

services:
  postgres:
    build: ./img-postgre-custom
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: lorenzo
      POSTGRES_PASSWORD: nefaissurtoutpasca
      POSTGRES_DB: LordOfDarkness
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - envdocker_my_network
  
  build_frontend:
    image: node:22
    container_name: build_frontend
    working_dir: /app
    volumes:
      - ../front:/app
      - ../envDocker/img-nginx-custom/prod:/dist
    command: sh -c "npm install && npm run build && cp -r /app/dist/* /dist/"

  nginx:
    build: 
      context: ../
      dockerfile: envDocker/img-nginx-custom/dockerfile
    restart: always
    container_name: nginx
    ports:
      - "3100:80"
    depends_on:
      - postgres
    networks:
      - envdocker_my_network

  api:
    build: ../back
    restart: always
    container_name: api
    ports:
      - "3200:3200"
    networks:
      - envdocker_my_network

networks:
  envdocker_my_network:
    driver: bridge

volumes:
  postgres_data:
